version: '2'

services:
  app:
    image: zo-simple-hard-counter
    build: .
    command: node index.js
    ports:
      - 3000:3000
    links:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: zo
      POSTGRES_USER: zo
      POSTGRES_DB: zo
      REDIS_HOST: redis

  redis:
    image: redis:3.0.7-alpine

  postgres:
    image: postgres:9.6.1-alpine
    ports:
      - 25432:5432
    environment:
      POSTGRES_PASSWORD: zo
      POSTGRES_USER: zo
      POSTGRES_DB: zo

